### ISSUE TITLE
Create a 1.8 branch so I can PR :)

### ISSUE THREAD

**Issue by ChrisLane** [squeek502/Squeedometer#2]

**Comment by squeek502** [comment]
Appreciate the update, but I'm not sure I want to merge it as-is.
- I prefer my directory structure to gradle's default (java instead of src/main/java).
- I also intentionally created the build.gradle file to be mod-version independent, so that I don't have to commit anything when I release a new version. Not sure why I left off the build instructions from this repo's README, though, so sorry about that not being clear (see, for example, https://github.com/squeek502/WailaHarvestability#building).

If you could just commit the 1.8 java file updates as a stand-alone commit (without the directory structure changes) and PR that, I'd gladly accept it, though.

I'll create a new branch once I get the chance; can't seem to do it through the web interface.

**Comment by ChrisLane** [comment]
Fair enough, will do :)

**Comment by squeek502** [comment]
Great, thanks. [Created the branch](https://github.com/squeek502/Squeedometer/tree/1.8.x), so feel free to PR whenever you're ready.
